package com.kurage.api.domain.enums;

public enum NotificationType {
    SYSTEM,
    PLATFORM_ANNOUNCEMENT,
    PLATFORM_SUGGESTION,
    PLATFORM_DISCOVERY,
    TEAM_INVITE,
    TEAM_ROLE_UPDATE,
    TEAM_CREATED,
    TEAM_JOIN_REQUEST,
    TEAM_JOIN_APPROVED,
    TEAM_JOIN_REJECTED,
    TEAM_INVITE_LINK_USED,
    FRIEND_REQUEST,
    FRIEND_REQUEST_ACCEPTED
}
