"""Rebuild the Kurage knowledge graph in graphify-out/.

Run this instead of `graphify update .`. The plain CLI rescans the whole
repository, which pulls in `docs/en` — a translation of `docs/pt` that duplicates
every concept node — and drops the curated community labels and the documented
invariants layer. This script keeps all three.

    python tools/graphify/rebuild.py

Requires the graphify package. Install with:

    uv tool install "graphifyy[sql,terraform]"

Code is extracted structurally (AST): no API key and no token cost. The concept
nodes in rules.py are maintained by hand, not generated by a model.
"""

from __future__ import annotations

import collections
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from rules import build_semantic_layer  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "graphify-out"

# graphify is normally installed as an isolated uv/pipx tool, so the `python` on
# PATH usually cannot import it. Rather than making the caller hunt for the right
# interpreter, find it and re-exec this script under it.
_REEXEC_GUARD = "KURAGE_GRAPHIFY_REEXEC"


def _graphify_interpreter() -> str | None:
    """Return a Python that can import graphify, or None."""
    scripts = "Scripts" if os.name == "nt" else "bin"
    binary = "python.exe" if os.name == "nt" else "python"

    candidates: list[Path] = []
    sidecar = OUT / ".graphify_python"
    if sidecar.is_file():
        saved = sidecar.read_text(encoding="utf-8").strip().lstrip("﻿")
        if saved:
            candidates.append(Path(saved))
    for tool in ("uv", "pipx"):
        try:
            if tool == "uv":
                root = subprocess.run(["uv", "tool", "dir"], capture_output=True,
                                      text=True, timeout=30)
            else:
                root = subprocess.run(["pipx", "environment", "--value",
                                       "PIPX_LOCAL_VENVS"], capture_output=True,
                                      text=True, timeout=30)
        except (OSError, subprocess.SubprocessError):
            continue
        if root.returncode == 0 and root.stdout.strip():
            candidates.append(Path(root.stdout.strip()) / "graphifyy" / scripts / binary)

    for candidate in candidates:
        if not candidate.is_file():
            continue
        probe = subprocess.run([str(candidate), "-c", "import graphify"],
                               capture_output=True)
        if probe.returncode == 0:
            return str(candidate)
    return None


def _ensure_graphify() -> None:
    try:
        import graphify  # noqa: F401
        return
    except ImportError:
        pass
    if os.environ.get(_REEXEC_GUARD):
        print("ERROR: graphify is not importable. Install it with:\n"
              '    uv tool install "graphifyy[sql,terraform]"', file=sys.stderr)
        raise SystemExit(1)
    interpreter = _graphify_interpreter()
    if interpreter is None:
        print("ERROR: graphify is not installed. Install it with:\n"
              '    uv tool install "graphifyy[sql,terraform]"', file=sys.stderr)
        raise SystemExit(1)
    print(f"re-exec under {interpreter}")
    raise SystemExit(subprocess.run(
        [interpreter, str(Path(__file__).resolve()), *sys.argv[1:]],
        env={**os.environ, _REEXEC_GUARD: "1"}).returncode)

# Excluded on purpose:
#   docs/en          translation of docs/pt; would duplicate every concept node
#   frontend/public  144 CS2 skin thumbnails, no semantic content
#   README.en.md     translation
#   frontend/AGENTS.md  regenerated by `next dev`, not authored here
EXCLUDED_PREFIXES = ("graphify-out/", "docs/en/", "frontend/public/")
EXCLUDED_FILES = ("README.en.md", "frontend/AGENTS.md")

# Communities are numbered by the clustering algorithm and renumber on every
# rebuild, so these names are applied by matching a hub symbol instead of an id.
HUB_LABELS = {
    "TeamController": "Team Management API",
    "RateLimitingService": "Rate Limiting",
    "GlobalExceptionHandler": "Error Handling",
    "SteamAuthService": "Steam OpenID Handshake",
    "RefreshTokenService": "Refresh Token Rotation",
    "ImageUploadService": "Image Upload and R2 Storage",
    "NotificationService": "Notification Service",
    "SearchService": "Unified Search",
    "GameServerService": "Game Server Telemetry",
    "ProfileVisitService": "Profile Visits",
    "SubscriptionService": "Subscription Entitlements",
    "RankingService": "Ranking and Leaderboards",
    "InventoryService": "Inventory",
    "PlayerStats": "Player Stats and Calibration",
}

AREA_LABELS = [
    ("backend/src/main/java/com/kurage/api/controller", "API Controllers"),
    ("backend/src/main/java/com/kurage/api/service", "Backend Services"),
    ("backend/src/main/java/com/kurage/api/repository", "JPA Repositories"),
    ("backend/src/main/java/com/kurage/api/domain", "Domain Entities"),
    ("backend/src/main/java/com/kurage/api/dto", "API Contracts"),
    ("backend/src/main/java/com/kurage/api/security", "Backend Security"),
    ("backend/src/main/java/com/kurage/api/config", "Backend Config"),
    ("backend/src/main/java/com/kurage/api/exception", "Error Handling"),
    ("backend/src/main/resources/db", "Flyway Migrations"),
    ("backend/src/test", "Backend Tests"),
    ("frontend/src/components/profile", "Profile UI"),
    ("frontend/src/components/search", "Search UI"),
    ("frontend/src/components/home", "Home UI"),
    ("frontend/src/components/shell", "App Shell UI"),
    ("frontend/src/components/ui", "Shared UI Primitives"),
    ("frontend/src/components", "Frontend Components"),
    ("frontend/src/app", "Next.js Routes"),
    ("frontend/src/lib", "Frontend Lib"),
    ("frontend/src/types", "Frontend Types"),
    ("frontend/src/__tests__", "Frontend Tests"),
    ("frontend", "Frontend"),
    ("server/plugins", "CS2 Plugins"),
    ("server/profiles", "CS2 Server Profiles"),
    ("infra", "Infrastructure"),
    ("docs/pt", "Documented Invariants"),
    ("faceit-levels", "FACEIT Level Assets"),
    (".github", "CI Workflows"),
]


def _relative(path: str) -> str | None:
    try:
        return Path(path).resolve().relative_to(REPO).as_posix()
    except ValueError:
        return None


def _keep(path: str) -> bool:
    rel = _relative(path)
    if rel is None:
        return False
    if rel in EXCLUDED_FILES:
        return False
    return not rel.startswith(EXCLUDED_PREFIXES)


def _area_of(source_file: str) -> str | None:
    src = (source_file or "").replace("\\", "/")
    for prefix, name in AREA_LABELS:
        if src.startswith(prefix):
            return name
    return None


def main() -> int:
    _ensure_graphify()

    from graphify.analyze import god_nodes, suggest_questions, surprising_connections
    from graphify.build import build_from_json
    from graphify.cluster import cluster, score_all
    from graphify.detect import detect, save_manifest
    from graphify.diagnostics import diagnose_extraction
    from graphify.export import to_json
    from graphify.extract import collect_files, extract
    from graphify.report import generate

    OUT.mkdir(exist_ok=True)

    detection = detect(REPO)
    code = [f for f in detection["files"].get("code", []) if _keep(f)]
    docs = [f for f in detection["files"].get("document", []) if _keep(f)]
    detection["files"] = {
        "code": code, "document": docs, "paper": [], "image": [], "video": [],
    }
    detection["total_files"] = len(code) + len(docs)
    (OUT / ".graphify_detect.json").write_text(
        json.dumps(detection, ensure_ascii=False), encoding="utf-8")
    print(f"corpus: {len(code)} code, {len(docs)} docs")

    code_paths: list[Path] = []
    for f in code:
        p = Path(f)
        code_paths.extend(collect_files(p) if p.is_dir() else [p])
    ast = extract(code_paths, cache_root=REPO, parallel=False)
    print(f"AST: {len(ast['nodes'])} nodes, {len(ast['edges'])} edges")

    semantic = build_semantic_layer(REPO)
    known = {n["id"] for n in ast["nodes"]} | {n["id"] for n in semantic["nodes"]}
    orphans = [
        ref
        for edge in semantic["edges"]
        for ref in (edge["source"], edge["target"])
        if ref not in known
    ]
    orphans += [
        ref
        for hyper in semantic["hyperedges"]
        for ref in hyper["nodes"]
        if ref not in known
    ]
    if orphans:
        print("ERROR: invariant layer references nodes that do not exist:")
        for ref in sorted(set(orphans)):
            print(f"  {ref}")
        print("A renamed or moved symbol breaks these links. Fix rules.py.")
        return 1
    print(f"invariants: {len(semantic['nodes'])} concepts, "
          f"{len(semantic['edges'])} edges (all targets verified)")

    seen = {n["id"] for n in ast["nodes"]}
    nodes = list(ast["nodes"])
    for node in semantic["nodes"]:
        if node["id"] not in seen:
            nodes.append(node)
            seen.add(node["id"])
    merged = {
        "nodes": nodes,
        "edges": ast["edges"] + semantic["edges"],
        "hyperedges": semantic["hyperedges"],
        "input_tokens": 0,
        "output_tokens": 0,
    }
    (OUT / ".graphify_extract.json").write_text(
        json.dumps(merged, indent=2, ensure_ascii=False), encoding="utf-8")

    graph = build_from_json(merged, root=str(REPO), directed=False)
    if graph.number_of_nodes() == 0:
        print("ERROR: extraction produced an empty graph")
        return 1
    communities = cluster(graph)
    cohesion = score_all(graph, communities)

    by_id = {n["id"]: n for n in nodes}
    labels: dict[int, str] = {}
    used: collections.Counter[str] = collections.Counter()
    for cid, members in communities.items():
        chosen = None
        for member in members:
            node = by_id.get(member)
            if node and node.get("label") in HUB_LABELS:
                chosen = HUB_LABELS[node["label"]]
                break
        if chosen is None:
            areas: collections.Counter[str] = collections.Counter()
            for member in members:
                node = by_id.get(member)
                area = _area_of(node.get("source_file", "")) if node else None
                if area:
                    areas[area] += 1
            chosen = areas.most_common(1)[0][0] if areas else "External Symbols"
        used[chosen] += 1
        labels[cid] = chosen if used[chosen] == 1 else f"{chosen} {used[chosen]}"

    gods = god_nodes(graph)
    surprises = surprising_connections(graph, communities)
    questions = suggest_questions(graph, communities, labels)
    if not to_json(graph, communities, str(OUT / "graph.json"),
                   community_labels=labels):
        print("ERROR: refused to shrink graph.json; delete it to force a rebuild")
        return 1
    (OUT / "GRAPH_REPORT.md").write_text(
        generate(graph, communities, cohesion, labels, gods, surprises, detection,
                 {"input": 0, "output": 0}, str(REPO),
                 suggested_questions=questions),
        encoding="utf-8")
    (OUT / ".graphify_labels.json").write_text(
        json.dumps({str(k): v for k, v in labels.items()},
                   ensure_ascii=False, indent=2), encoding="utf-8")
    (OUT / ".graphify_analysis.json").write_text(
        json.dumps({
            "communities": {str(k): v for k, v in communities.items()},
            "cohesion": {str(k): v for k, v in cohesion.items()},
            "gods": gods, "surprises": surprises, "questions": questions,
        }, indent=2, ensure_ascii=False), encoding="utf-8")

    corpus = {"code": code, "document": docs}
    save_manifest({"code": code}, root=str(REPO),
                  scan_corpus={f for files in corpus.values() for f in files})

    health = diagnose_extraction(merged, directed=False, root=str(REPO))
    print(f"graph: {graph.number_of_nodes()} nodes, {graph.number_of_edges()} edges, "
          f"{len(communities)} communities")
    print(f"health: dangling={health.get('dangling_endpoint_edges')} "
          f"missing={health.get('missing_endpoint_edges')} "
          f"self_loops={health.get('self_loop_edges')}")
    print("dangling edges point at framework types outside the corpus "
          "(Spring, Jakarta, java.*) and are expected.")
    print("\nNext: `graphify export html` and `graphify export wiki` to refresh "
          "the browsable outputs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
