<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Kurage.Core</AssemblyName>
    <RootNamespace>Kurage.Core</RootNamespace>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <!-- CounterStrikeSharp Official API Package -->
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
    <ProjectReference Include="..\Kurage.Core.Contracts\Kurage.Core.Contracts.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
