<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Kurage.Core.Contracts</AssemblyName>
    <RootNamespace>Kurage.Core.Contracts</RootNamespace>
  </PropertyGroup>

</Project>
